# Generated by Django 4.1.7 on 2023-03-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_owner_alter_pokemon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
